### ISSUE TITLE
教学计划变更

### ISSUE THREAD

**Issue by ChenMeiXiao** [jwgl/bell-tm-place#42]
1、在“待处理”和”已处理”里，不要显示教室借用申请，只显示教学计划变更，方便查询教学计划变更事项。
2、教学计划变更里，流程没有到领导审核项。
3、显示教学计划变更里，把学院申请变更理由显示在教学计划最下面，不要在另外页面流程里显示。

**Comment by todoubaba** [comment]
请在[这里](https://github.com/jwgl/bell-tm-plan/issues)提交关于教学计划的问题，并分项提交。
